apiVersion: v1
name: probate-orchestrator-service
home: https://github.com/hmcts/probate-orchestrator-service
version: 1.0.3
description: HMCTS Probate Orchestrator Service
maintainers:
  - name: HMCTS Probate Team
    email: Probate@hmcts.net